server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/greengrocer?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  mvc:
    static-path-pattern: /static/**
    hiddenmethod:
      filter:
        enabled: true
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



